owner: geometry-labs
repo: icon-status-page # The name of this repository

sites:
  - name: Dev Tracker Frontend
    url: https://explorer.icon.geometry-dev.net/
  - name: Dev Blocks Service
    url: https://explorer.icon.geometry-dev.net/api/v1/blocks
  - name: Dev Transactions Service
    url: https://explorer.icon.geometry-dev.net/api/v1/transactions
  - name: Dev Logs Service
    url: https://explorer.icon.geometry-dev.net/api/v1/logs
  - name: Dev Addresses Service
    url: https://explorer.icon.geometry-dev.net/api/v1/addresses
  - name: Dev Governance Service
    url: https://explorer.icon.geometry-dev.net/api/v1/governance/preps
  - name: Dev Contracts Service
    url: https://explorer.icon.geometry-dev.net/api/v1/contracts
  - name: Dev Metrics Service
    url: https://explorer.icon.geometry-dev.net/api/v1/metrics/supply


status-website:
  cname: status.icon.geometry.io
  logoUrl: https://raw.githubusercontent.com/geometry-labs/icon-status-page/master/assets/icon-logo.png
  name: Upptime
  introTitle: |
    Status page for the **ICON Blockchain**
    Endpoints supported by **Geometry Labs**
  introMessage: TODO
  navbar:
    - title: Status
      href: /
    - title: Kibana
      href: https://kibana.icon.geometry.io
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

